# Добро пожаловать в Джекилл!
#
# Этот конфигурационный файл предназначен для настроек, которые влияют на весь ваш блог, значения
# который вы должны настроить один раз и редко редактировать после этого. Если вы найдете
# вы сами очень часто редактируете этот файл, подумайте об использовании файлов данных Джекила
# функция для данных, которые вам нужно часто обновлять.
#
# По техническим причинам этот файл *не * перезагружается автоматически при использовании
# 'пакет старпома Джекил "служить". Если вы измените этот файл, пожалуйста, перезагрузите серверный процесс.

# Параметр сайта
# Они используются для персонализации вашего нового сайта. Если вы посмотрите в HTML файлы,
# вы увидите, что они доступны через {{ сайт.название }}, {{ сайт.электронная почта }} и так далее.
# Вы можете создать любую пользовательскую переменную, которую вы хотите, и они будут доступны
# в шаблонах через {{ сайт.значение MyVariable }}.
title: Olimp
description: > # this means to ignore newlines until "baseurl:"
  Здесь вы найдете обучающие материалы по экосистеме Java.
baseurl: "/"
url: "https://krylovsergey1999.github.io"
permalink: /:year/:month/:day/:title
repository: krylovsergey1999/krylovsergey1999
paginate: 5

# MatJek specific configurations
github_profile: "https://github.com/krylovsergey1999"
user: "Krylov Sergey"
user_email: "https://vk.com/kssergey2"
google_tracking_id: "UA-96359860-1"
google_site_verification: "UA-96359860-1"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
